global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: minispace_api
    static_configs:
      - targets: ["api:8080"]
    metrics_path: /metrics

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
